let students = [
  {
    name: "Abdikadir Samatar",
    group: "App Dev Team",
    github: "https://github.com/abdikadirsamatar",
    linkedin: "https://www.linkedin.com/in/abdikadir-samatar/",
    email: "asamatar@appdev.yearup.org",
    nickname: "deer",
    imageurl: "https://fakeimg.pl/600x400?text=deer",
    gender: "male",
    devices: "MAC",
    xp: 0,
    currentlyWorkingOn: 20,
  },
  {
    name: "Dante 'Donny' Angerame",
    group: "App Dev Team",
    github: "https://github.com/DanteAngerame",
    linkedin: "https://www.linkedin.com/in/dante-angerame-739899192/",
    email: "dangerame@appdev.yearup.org",
    nickname: "The Woodchuck",
    imageurl: "https://a-z-animals.com/media/2021/10/groundhog-1024x535.jpg",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 42,
  },
  {
    name: "Guadalupe Argumedo Saucedo",
    group: "App Dev Team",
    github: "https://github.com/GuadalupeArgumedoSaucedo",
    linkedin:
      "https://www.linkedin.com/in/guadalupe-argumedo-saucedo-2b63b8303/",
    email: "gargumedosaucedo@appdev.yearup.org",
    nickname: "CodeLupe",
    imageurl: "https://fakeimg.pl/600x400?text=CodeLupe",
    gender: "female",
    devices: "MAC",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Jaranesca Braker",
    group: "App Dev Team",
    github: "https://github.com/jaranesca",
    linkedin: "https://www.linkedin.com/in/jaranesca-braker-227810253/",
    email: "jbraker@appdev.yearup.org",
    nickname: "JSJ (JavaScript Jaranesca)",
    imageurl: "https://fakeimg.pl/600x400?text=JSJ%20(JavaScript%20Jaranesca)",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Jesús Mimila",
    group: "App Dev Team",
    github: "https://github.com/JesusMimilaHurtado",
    linkedin: "https://www.linkedin.com/in/jesus-mimils-435b32274/",
    email: "jmimila@appdev.yearup.org",
    nickname: "JJ",
    imageurl: "https://fakeimg.pl/600x400?text=JJ",
    devices: "MAC",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Kaaliyah Gray (Mac)",
    group: "App Dev Team",
    github: "https://github.com/KaaliyahGray",
    linkedin: "https://www.linkedin.com/in/kaaliyahgray-b03281237",
    email: "kgray@appdev.yearup.org",
    nickname: "leetheMrE",
    imageurl: "https://fakeimg.pl/600x400?text=leetheMrE",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Kadiatou Barry (Mac)",
    group: "App Dev Team",
    github: "https://github.com/kadylius/kadi-barry",
    linkedin: "https://www.linkedin.com/in/kadiatou-barry-a57bb8235/",
    email: "kbarry@appdev.yearup.org",
    nickname: "the connoisseur",
    imageurl: "https://fakeimg.pl/600x400?text=the%20connoisseur",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Kayla Hanifen (Mac)",
    group: "App Dev Team",
    github: "https://github.com/KaylaEHanifen",
    linkedin: "https://www.linkedin.com/in/kehanifen",
    email: "khanifen@appdev.yearup.org",
    nickname: "Agent K",
    imageurl: "https://fakeimg.pl/600x400?text=Agent%20K",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Leslie Alvarado (Mac)",
    group: "App Dev Team",
    github: "https://github.com/LeslieAlvarado1",
    linkedin: "https://www.linkedin.com/in/leslie-alvarado-connect/",
    email: "lalvarado@appdev.yearup.org",
    nickname: "The ScriptSiren",
    imageurl: "https://fakeimg.pl/600x400?text=The%20ScriptSiren",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Maximo Mayo",
    group: "App Dev Team",
    github: "https://github.com/MaximoMayo",
    linkedin: "https://www.linkedin.com/in/maximo-mayo-a2ba10252/",
    email: "mmayo@appdev.yearup.org",
    nickname: "reference error",
    imageurl: "https://fakeimg.pl/600x400?text=reference%20error",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Moncerrat Lua Salas",
    group: "App Dev Team",
    github: "https://github.com/MoncerratLuaSalas",
    linkedin: "https://www.linkedin.com/in/moncerrat-lua-salas/",
    email: "mluasalas@appdev.yearup.org",
    nickname: "Monce",
    imageurl: "https://fakeimg.pl/600x400?text=Monce",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Niran Abdulqader",
    group: "App Dev Team",
    github: "https://github.com/NiranAbdulqader",
    linkedin: "https://www.linkedin.com/in/niran-abdulqader-/",
    email: "nabdulqader@appdev.yearup.org",
    nickname: "Techie Diva",
    imageurl: "https://fakeimg.pl/600x400?text=Techie%20Diva",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Rene Banuelos",
    group: "App Dev Team",
    github: "https://github.com/ReneBA1999",
    linkedin: "https://www.linkedin.com/in/rene-banuelos-1881b52a2",
    email: "rbanuelos@appdev.yearup.org",
    nickname: "Cyber Samurai",
    imageurl: "https://fakeimg.pl/600x400?text=Cyber%20Samurai",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Sabrina Robles",
    group: "App Dev Team",
    github: "https://github.com/SabrinaRobles",
    linkedin: "https://www.linkedin.com/in/sabrinarobles/",
    email: "srobles@appdev.yearup.org",
    nickname: "Sabritron",
    imageurl: "https://fakeimg.pl/600x400?text=Sabritron",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Uriel Delgado",
    group: "App Dev Team",
    github: "https://github.com/UrielDelgado",
    linkedin: "https://www.linkedin.com/in/uriel-delgado-3a49622bb/",
    email: "udelgado@appdev.yearup.org",
    nickname: "YaBoiUri",
    imageurl: "https://fakeimg.pl/600x400?text=YaBoiUri",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Victor Castaneda",
    group: "App Dev Team",
    github: "https://github.com/Victor-Castaneda",
    linkedin: "https://www.linkedin.com/in/victor-castaneda/",
    email: "vcastaneda@appdev.yearup.org",
    nickname: "Victorious Victor",
    imageurl: "https://fakeimg.pl/600x400?text=Victorious%20Victor",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
  {
    name: "Remsey Mailjard",
    group: "IT Solutions Group",
    github: "https://github.com/RemseyMailjard",
    linkedin: "https://www.linkedin.com/in/remseymailjard/",
    email: "remsey@skills4-it.nl",
    nickname: "Mailjard the Magnificent",
    imageurl: "https://fakeimg.pl/600x400?text=Mailjard%20the%20Magnificent",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: "Page nr",
  },
];
